import { playerSkill, tierDefaults } from "./manifestHelpers";

export const MOVEMENT_SKILLS = [
  playerSkill({
    id: "move_shadow_step",
    skillType: "movement",
    ...tierDefaults(2),
    stringId: "skills.move.shadow_step",
    icon: "👟",
    mpCost: 10,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 55,
    cooldownTurns: 1,
    damageMultiplier: 1,
    accuracyBonus: 30,
    selfStatus: { type: "def_buff", turns: 1, magnitude: 0.25 },
  }),
  playerSkill({
    id: "move_dodge_roll",
    skillType: "movement",
    ...tierDefaults(3),
    stringId: "skills.move.dodge_roll",
    icon: "🌀",
    mpCost: 14,
    kind: "buff",
    targetType: "self",
    autoPriority: 60,
    cooldownTurns: 2,
    selfStatus: { type: "def_buff", turns: 2, magnitude: 0.4 },
  }),
  playerSkill({
    id: "move_cavalry_charge",
    skillType: "movement",
    ...tierDefaults(4),
    stringId: "skills.move.cavalry_charge",
    icon: "🐎",
    mpCost: 26,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 82,
    cooldownTurns: 4,
    damageMultiplier: 1.55,
    guaranteedStatus: "stun",
    statusProcBonus: 0.15,
  }),
  playerSkill({
    id: "move_flash_step",
    skillType: "movement",
    ...tierDefaults(5),
    stringId: "skills.move.flash_step",
    icon: "⚡",
    mpCost: 20,
    kind: "buff",
    targetType: "self",
    autoPriority: 58,
    cooldownTurns: 3,
    gaugeBoost: 25,
  }),
] as const;
