import { playerSkill, tierDefaults } from "./manifestHelpers";

export const PASSIVE_SKILLS = [
  playerSkill({
    id: "passive_sturdy_frame",
    skillType: "passive",
    ...tierDefaults(1),
    stringId: "skills.passive.sturdy_frame",
    icon: "🛡",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [{ stat: "maxHp", magnitude: 0.06 }],
  }),
  playerSkill({
    id: "passive_blade_mastery",
    skillType: "passive",
    ...tierDefaults(2),
    stringId: "skills.passive.blade_mastery",
    icon: "⚔",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [{ stat: "atk", magnitude: 0.05 }],
  }),
  playerSkill({
    id: "passive_arcane_mind",
    skillType: "passive",
    ...tierDefaults(2),
    stringId: "skills.passive.arcane_mind",
    icon: "🔮",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [{ stat: "maxMp", magnitude: 0.08 }],
  }),
  playerSkill({
    id: "passive_swift_feet",
    skillType: "passive",
    ...tierDefaults(3),
    stringId: "skills.passive.swift_feet",
    icon: "👟",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [
      { stat: "speed", magnitude: 8 },
      { stat: "evasion", magnitude: 2 },
    ],
  }),
  playerSkill({
    id: "passive_keen_eye",
    skillType: "passive",
    ...tierDefaults(3),
    stringId: "skills.passive.keen_eye",
    icon: "👁",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [
      { stat: "critChance", magnitude: 0.04 },
      { stat: "accuracy", magnitude: 8 },
    ],
  }),
  playerSkill({
    id: "passive_guardian_aura",
    skillType: "passive",
    ...tierDefaults(4),
    stringId: "skills.passive.guardian_aura",
    icon: "🛡",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [
      { stat: "def", magnitude: 0.06 },
      { stat: "statusResist", magnitude: 0.04 },
    ],
  }),
  playerSkill({
    id: "passive_brutal_strikes",
    skillType: "passive",
    ...tierDefaults(5),
    stringId: "skills.passive.brutal_strikes",
    icon: "💥",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [{ stat: "critDamage", magnitude: 0.1 }],
  }),
] as const;
