import { playerSkill, tierDefaults } from "./manifestHelpers";

export const ACTIVE_SKILLS = [
  playerSkill({
    id: "active_power_slash",
    skillType: "active",
    ...tierDefaults(1),
    stringId: "skills.active.power_slash",
    icon: "⚔",
    mpCost: 8,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 60,
    cooldownTurns: 1,
    damageMultiplier: 1.2,
  }),
  playerSkill({
    id: "active_iron_palm",
    skillType: "active",
    ...tierDefaults(2),
    stringId: "skills.active.iron_palm",
    icon: "✊",
    mpCost: 12,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 70,
    cooldownTurns: 2,
    damageMultiplier: 1.3,
    defPierce: 0.05,
    guaranteedStatus: "bleed",
    statusProcBonus: 0.1,
  }),
  playerSkill({
    id: "active_arcane_bolt",
    skillType: "active",
    ...tierDefaults(3),
    stringId: "skills.active.arcane_bolt",
    icon: "✨",
    mpCost: 16,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 75,
    cooldownTurns: 1,
    damageMultiplier: 1.35,
    defPierce: 0.2,
  }),
  playerSkill({
    id: "active_inner_qi",
    skillType: "active",
    ...tierDefaults(4),
    stringId: "skills.active.inner_qi",
    icon: "🔥",
    mpCost: 22,
    kind: "buff",
    targetType: "self",
    autoPriority: 50,
    cooldownTurns: 3,
    selfStatus: { type: "atk_buff", turns: 2, magnitude: 0.18 },
  }),
  playerSkill({
    id: "active_holy_light",
    skillType: "active",
    ...tierDefaults(5),
    stringId: "skills.active.holy_light",
    icon: "✝",
    mpCost: 26,
    kind: "heal",
    targetType: "self",
    autoPriority: 85,
    cooldownTurns: 3,
    healPercent: 0.24,
  }),
  playerSkill({
    id: "active_dragon_fist",
    skillType: "active",
    ...tierDefaults(6),
    stringId: "skills.active.dragon_fist",
    icon: "🐉",
    mpCost: 32,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 90,
    cooldownTurns: 4,
    damageMultiplier: 1.75,
    defPierce: 0.45,
    guaranteedStatus: "bleed",
    statusProcBonus: 0.2,
  }),
  playerSkill({
    id: "active_meteor",
    skillType: "active",
    ...tierDefaults(7),
    stringId: "skills.active.meteor",
    icon: "☄",
    mpCost: 38,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 95,
    cooldownTurns: 5,
    damageMultiplier: 1.95,
    defPierce: 0.55,
  }),
] as const;
