import type { PassiveEffect, SkillDefinition } from "../types";
import type { SkillType } from "../skillTypes";

export const CATALOG_VERSION = 3;

const UNLOCK_BY_TIER = [1, 5, 10, 15, 20, 25, 30] as const;
const SP_BY_TIER = [1, 2, 4, 6, 8, 10, 12] as const;

function tierDefaults(tier: number) {
  const idx = Math.min(Math.max(tier - 1, 0), 6);
  return {
    catalogTier: tier,
    unlockLevel: UNLOCK_BY_TIER[idx],
    unlockSpCost: SP_BY_TIER[idx],
    slotTier: Math.min(tier, 4) as 1 | 2 | 3 | 4,
  };
}

function playerSkill(
  partial: Omit<SkillDefinition, "path"> & { skillType: SkillType }
): SkillDefinition {
  const { skillType, ...rest } = partial;
  return { ...rest, path: "player", skillType };
}

export const PLAYER_SKILL_MANIFEST: SkillDefinition[] = [
  playerSkill({
    id: "active_power_slash",
    skillType: "active",
    ...tierDefaults(1),
    stringId: "skills.active.power_slash",
    icon: "⚔",
    mpCost: 8,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 60,
    cooldownTurns: 1,
    damageMultiplier: 1.2,
  }),
  playerSkill({
    id: "active_iron_palm",
    skillType: "active",
    ...tierDefaults(2),
    stringId: "skills.active.iron_palm",
    icon: "✊",
    mpCost: 12,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 70,
    cooldownTurns: 2,
    damageMultiplier: 1.3,
    defPierce: 0.05,
    guaranteedStatus: "bleed",
    statusProcBonus: 0.1,
  }),
  playerSkill({
    id: "active_arcane_bolt",
    skillType: "active",
    ...tierDefaults(3),
    stringId: "skills.active.arcane_bolt",
    icon: "✨",
    mpCost: 16,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 75,
    cooldownTurns: 1,
    damageMultiplier: 1.35,
    defPierce: 0.2,
  }),
  playerSkill({
    id: "active_inner_qi",
    skillType: "active",
    ...tierDefaults(4),
    stringId: "skills.active.inner_qi",
    icon: "🔥",
    mpCost: 22,
    kind: "buff",
    targetType: "self",
    autoPriority: 50,
    cooldownTurns: 3,
    selfStatus: { type: "atk_buff", turns: 2, magnitude: 0.18 },
  }),
  playerSkill({
    id: "active_holy_light",
    skillType: "active",
    ...tierDefaults(5),
    stringId: "skills.active.holy_light",
    icon: "✝",
    mpCost: 26,
    kind: "heal",
    targetType: "self",
    autoPriority: 85,
    cooldownTurns: 3,
    healPercent: 0.24,
  }),
  playerSkill({
    id: "active_dragon_fist",
    skillType: "active",
    ...tierDefaults(6),
    stringId: "skills.active.dragon_fist",
    icon: "🐉",
    mpCost: 32,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 90,
    cooldownTurns: 4,
    damageMultiplier: 1.75,
    defPierce: 0.45,
    guaranteedStatus: "bleed",
    statusProcBonus: 0.2,
  }),
  playerSkill({
    id: "active_meteor",
    skillType: "active",
    ...tierDefaults(7),
    stringId: "skills.active.meteor",
    icon: "☄",
    mpCost: 38,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 95,
    cooldownTurns: 5,
    damageMultiplier: 1.95,
    defPierce: 0.55,
  }),
  playerSkill({
    id: "passive_sturdy_frame",
    skillType: "passive",
    ...tierDefaults(1),
    stringId: "skills.passive.sturdy_frame",
    icon: "🛡",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [{ stat: "maxHp", magnitude: 0.06 }],
  }),
  playerSkill({
    id: "passive_blade_mastery",
    skillType: "passive",
    ...tierDefaults(2),
    stringId: "skills.passive.blade_mastery",
    icon: "⚔",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [{ stat: "atk", magnitude: 0.05 }],
  }),
  playerSkill({
    id: "passive_arcane_mind",
    skillType: "passive",
    ...tierDefaults(2),
    stringId: "skills.passive.arcane_mind",
    icon: "🔮",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [{ stat: "maxMp", magnitude: 0.08 }],
  }),
  playerSkill({
    id: "passive_swift_feet",
    skillType: "passive",
    ...tierDefaults(3),
    stringId: "skills.passive.swift_feet",
    icon: "👟",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [
      { stat: "speed", magnitude: 8 },
      { stat: "evasion", magnitude: 2 },
    ],
  }),
  playerSkill({
    id: "passive_keen_eye",
    skillType: "passive",
    ...tierDefaults(3),
    stringId: "skills.passive.keen_eye",
    icon: "👁",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [
      { stat: "critChance", magnitude: 0.04 },
      { stat: "accuracy", magnitude: 8 },
    ],
  }),
  playerSkill({
    id: "passive_guardian_aura",
    skillType: "passive",
    ...tierDefaults(4),
    stringId: "skills.passive.guardian_aura",
    icon: "🛡",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [
      { stat: "def", magnitude: 0.06 },
      { stat: "statusResist", magnitude: 0.04 },
    ],
  }),
  playerSkill({
    id: "passive_brutal_strikes",
    skillType: "passive",
    ...tierDefaults(5),
    stringId: "skills.passive.brutal_strikes",
    icon: "💥",
    mpCost: 0,
    kind: "buff",
    targetType: "self",
    autoPriority: 0,
    cooldownTurns: 0,
    passiveEffects: [{ stat: "critDamage", magnitude: 0.1 }],
  }),
  playerSkill({
    id: "cc_shield_bash",
    skillType: "cc",
    ...tierDefaults(2),
    stringId: "skills.cc.shield_bash",
    icon: "🛡",
    mpCost: 14,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 80,
    cooldownTurns: 3,
    damageMultiplier: 1.2,
    defPierce: 0.1,
    guaranteedStatus: "stun",
  }),
  playerSkill({
    id: "cc_frost_nova",
    skillType: "cc",
    ...tierDefaults(3),
    stringId: "skills.cc.frost_nova",
    icon: "❄",
    mpCost: 18,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 78,
    cooldownTurns: 2,
    damageMultiplier: 1,
    defPierce: 0.15,
    guaranteedStatus: "freeze",
  }),
  playerSkill({
    id: "cc_silencing_word",
    skillType: "cc",
    ...tierDefaults(4),
    stringId: "skills.cc.silencing_word",
    icon: "🤐",
    mpCost: 22,
    kind: "buff",
    targetType: "enemy",
    autoPriority: 70,
    cooldownTurns: 3,
    guaranteedStatus: "silence",
  }),
  playerSkill({
    id: "cc_hamstring",
    skillType: "cc",
    ...tierDefaults(5),
    stringId: "skills.cc.hamstring",
    icon: "🦵",
    mpCost: 18,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 65,
    cooldownTurns: 2,
    damageMultiplier: 0.85,
    defPierce: 0.2,
    guaranteedStatus: "slow",
  }),
  playerSkill({
    id: "move_shadow_step",
    skillType: "movement",
    ...tierDefaults(2),
    stringId: "skills.move.shadow_step",
    icon: "👟",
    mpCost: 10,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 55,
    cooldownTurns: 1,
    damageMultiplier: 1,
    accuracyBonus: 30,
    selfStatus: { type: "def_buff", turns: 1, magnitude: 0.25 },
  }),
  playerSkill({
    id: "move_dodge_roll",
    skillType: "movement",
    ...tierDefaults(3),
    stringId: "skills.move.dodge_roll",
    icon: "🌀",
    mpCost: 14,
    kind: "buff",
    targetType: "self",
    autoPriority: 60,
    cooldownTurns: 2,
    selfStatus: { type: "def_buff", turns: 2, magnitude: 0.4 },
  }),
  playerSkill({
    id: "move_cavalry_charge",
    skillType: "movement",
    ...tierDefaults(4),
    stringId: "skills.move.cavalry_charge",
    icon: "🐎",
    mpCost: 26,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 82,
    cooldownTurns: 4,
    damageMultiplier: 1.55,
    guaranteedStatus: "stun",
    statusProcBonus: 0.15,
  }),
  playerSkill({
    id: "move_flash_step",
    skillType: "movement",
    ...tierDefaults(5),
    stringId: "skills.move.flash_step",
    icon: "⚡",
    mpCost: 20,
    kind: "buff",
    targetType: "self",
    autoPriority: 58,
    cooldownTurns: 3,
    gaugeBoost: 25,
  }),
];

export const LEGACY_SKILL_ID_MAP: Record<string, string> = {
  murim_palm: "active_iron_palm",
  murim_dash: "move_shadow_step",
  murim_qi: "active_inner_qi",
  murim_dragon: "active_dragon_fist",
  knight_slash: "active_power_slash",
  knight_guard: "passive_guardian_aura",
  knight_bash: "cc_shield_bash",
  knight_charge: "move_cavalry_charge",
  fantasy_bolt: "active_arcane_bolt",
  fantasy_freeze: "cc_frost_nova",
  fantasy_heal: "active_holy_light",
  fantasy_meteor: "active_meteor",
};

export function normalizeSkillId(skillId: string): string {
  return LEGACY_SKILL_ID_MAP[skillId] ?? skillId;
}

export function getSkillsByType(skillType: SkillType): SkillDefinition[] {
  return PLAYER_SKILL_MANIFEST.filter((s) => s.skillType === skillType);
}
