import { playerSkill, tierDefaults } from "./manifestHelpers";

export const CC_SKILLS = [
  playerSkill({
    id: "cc_shield_bash",
    skillType: "cc",
    ...tierDefaults(2),
    stringId: "skills.cc.shield_bash",
    icon: "🛡",
    mpCost: 14,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 80,
    cooldownTurns: 3,
    damageMultiplier: 1.2,
    defPierce: 0.1,
    guaranteedStatus: "stun",
  }),
  playerSkill({
    id: "cc_frost_nova",
    skillType: "cc",
    ...tierDefaults(3),
    stringId: "skills.cc.frost_nova",
    icon: "❄",
    mpCost: 18,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 78,
    cooldownTurns: 2,
    damageMultiplier: 1,
    defPierce: 0.15,
    guaranteedStatus: "freeze",
  }),
  playerSkill({
    id: "cc_silencing_word",
    skillType: "cc",
    ...tierDefaults(4),
    stringId: "skills.cc.silencing_word",
    icon: "🤐",
    mpCost: 22,
    kind: "buff",
    targetType: "enemy",
    autoPriority: 70,
    cooldownTurns: 3,
    guaranteedStatus: "silence",
  }),
  playerSkill({
    id: "cc_hamstring",
    skillType: "cc",
    ...tierDefaults(5),
    stringId: "skills.cc.hamstring",
    icon: "🦵",
    mpCost: 18,
    kind: "attack",
    targetType: "enemy",
    autoPriority: 65,
    cooldownTurns: 2,
    damageMultiplier: 0.85,
    defPierce: 0.2,
    guaranteedStatus: "slow",
  }),
] as const;
